{{- if .Values.services.changedetectionio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetectionio
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: changedetectionio
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.changedetectionio.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: changedetectionio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: changedetectionio
    spec:
      containers:
        - name: changedetectionio
          image: "{{ .Values.services.changedetectionio.image.repository }}:{{ .Values.services.changedetectionio.image.tag }}"
          imagePullPolicy: {{ .Values.services.changedetectionio.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
            - name: PLAYWRIGHT_DRIVER_URL
              value: "ws://playwright:{{ .Values.services.playwright.ports.http }}?stealth=1&--disable-web-security=true"
          ports:
            - name: http
              containerPort: {{ .Values.services.changedetectionio.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: changedetectionio-config
              mountPath: /config
              subPath: {{ .Values.services.changedetectionio.config }}

      volumes:
        - name: changedetectionio-config
          persistentVolumeClaim:
            claimName: longhorn-volv-pvc
{{- end }}
