{{- if .Values.services.bazarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: bazarr
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.bazarr.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bazarr
{{- end }}
