{{- if .Values.services.jellyfin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.jellyfin.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: "{{ .Values.services.jellyfin.image.repository }}:{{ .Values.services.jellyfin.image.tag }}"
          imagePullPolicy: {{ .Values.services.jellyfin.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
            - name: "JELLYFIN_PublishedServerUrl"
              value: "jellyfin.{{ .Values.services.traefik.domain }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.jellyfin.ports.http }}
              protocol: TCP
            - name: udp
              containerPort: {{ .Values.services.jellyfin.ports.udp }}
              protocol: UDP
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
              subPath: "{{ .Values.services.jellyfin.config }}"
            - name: library
              mountPath: /library
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: longhorn-volv-pvc
        - name: library
          hostPath:
            path: "{{ .Values.services.jellyfin.library }}"
            type: Directory
      {{- with .Values.services.jellyfin.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- with .Values.services.jellyfin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.jellyfin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with  .Values.services.jellyfin.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
