{{- if .Values.services.actualbudget.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: actualbudget
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: actualbudget
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.actualbudget.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: actualbudget
{{- end }}
