# templates/job-secret.yaml
{{- if and .Values.services.actualbudget.monoImporter.enabled .Values.services.actualbudget.monoImporter.job.secretParameters }}
apiVersion: v1
kind: Secret
metadata:
  name: mono-actual-job-secret
  labels:
    app.kubernetes.io/name: mono-actual
type: Opaque
data:
  {{- range $key, $value := .Values.services.actualbudget.monoImporter.job.secretParameters }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
