{{- if .Values.services.sonarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: sonarr
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.sonarr.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
        - name: sonarr
          image: "{{ .Values.services.sonarr.image.repository }}:{{ .Values.services.sonarr.image.tag }}"
          imagePullPolicy: {{ .Values.services.sonarr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.sonarr.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: data
              mountPath: /data

      volumes:
        - name: sonarr-config
          hostPath:
            path: "{{ .Values.services.sonarr.config }}"
            type: Directory
        - name: data
          hostPath:
            path: "{{ .Values.services.sonarr.data }}"
            type: Directory
{{- end }}
