{{- if .Values.services.mediamtx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: mediamtx
spec:
  type: ClusterIP
  ports:
    - name: rtsp
      port: {{ .Values.services.mediamtx.ports.rtsp }}
      targetPort: rtsp
      protocol: TCP
  selector:
    app.kubernetes.io/name: mediamtx
{{- end }}
