{{- $bot := .Values.services.monobankFirefly3Bot }}
{{- if or $bot.enabled $bot.cronSync.enabled $bot.historicalImport.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: monobank-firefly3-bot-config
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: monobank-firefly3-bot
data:
  config.json: {{ .Values.services.monobankFirefly3Bot.config | toJson | quote }}
{{- end }}
